package models

import "database/sql"

type RGPD_COLL struct {
	RgpdColCode      string  `json:"RGPD_COL_CODE"`
	ColIdentite      string  `json:"COL_IDENTITE"`
	ColEmail         string  `json:"COL_EMAIL"`
	ColTel           string  `json:"COL_TEL"`
	Cnracl           float64 `json:"CNRACL"`
	Rg               float64 `json:"RG"`
	Autre            float64 `json:"AUTRE"`
	Total            float64 `json:"TOTAL"`
	Facture1ErAnnee  int64   `json:"FACTURE_1ER_ANNEE"`
	Facture2EmeAnnee int64   `json:"FACTURE_2EME_ANNEE"`
	Facture3EmeAnnee int64   `json:"FACTURE_3EME_ANNEE"`
	Facture4EmeAnnee int64   `json:"FACTURE_4EME_ANNEE"`
	Facture5EmeAnnee int64   `json:"FACTURE_5EME_ANNEE"`
}

type RGPD_COLL_COMPLET struct {
	RgpdColCode string `json:"RGPD_COL_CODE"`
	ColIdentite string `json:"COL_IDENTITE"`
	ColEmail    string `json:"COL_EMAIL"`
	ColTel      string `json:"COL_TEL"`
}

type RGPD_COLL_SQL struct {
	RgpdColCode      string         `json:"RGPD_COL_CODE"`
	ColIdentite      string         `json:"COL_IDENTITE"`
	ColEmail         sql.NullString `json:"COL_EMAIL"`
	ColTel           sql.NullString `json:"COL_TEL"`
	Cnracl           float64        `json:"CNRACL"`
	Rg               float64        `json:"RG"`
	Autre            float64        `json:"AUTRE"`
	Total            float64        `json:"TOTAL"`
	Facture1ErAnnee  int64          `json:"FACTURE_1ER_ANNEE"`
	Facture2EmeAnnee int64          `json:"FACTURE_2EME_ANNEE"`
	Facture3EmeAnnee int64          `json:"FACTURE_3EME_ANNEE"`
	Facture4EmeAnnee int64          `json:"FACTURE_4EME_ANNEE"`
	Facture5EmeAnnee int64          `json:"FACTURE_5EME_ANNEE"`
}

type RGPD_COLL_COMPLET_SQL struct {
	RgpdColCode string         `json:"RGPD_COL_CODE"`
	ColIdentite string         `json:"COL_IDENTITE"`
	ColEmail    sql.NullString `json:"COL_EMAIL"`
	ColTel      sql.NullString `json:"COL_TEL"`
}

// Generated by https://quicktype.io

// type Etudepaye struct {
// 	EtudepayeID          int64  `json:"etudepaye_Id"`
// 	EtudepayeColCode     string `json:"etudepaye_col_code"`
// 	EtudepayeNbpaye      int64  `json:"etudepaye_nbpaye"`
// 	EtudepayeMission     string `json:"etudepaye_mission"`
// 	EtudepayeCommentaire string `json:"etudepaye_commentaire"`
// }

// Generated by https://quicktype.io

type Etudepaye struct {
	EtudepayeColCode     string `json:"etudepaye_col_code"`
	ColIdentite          string `json:"COL_IDENTITE"`
	ColEmail             string `json:"COL_EMAIL"`
	ColTel               string `json:"COL_TEL"`
	EtudepayeNbpaye      int64  `json:"etudepaye_nbpaye"`
	EtudepayeMission     string `json:"etudepaye_mission"`
	EtudepayeCommentaire string `json:"etudepaye_commentaire"`
}

type NewEtudepaye struct {
	EtudepayeId               string
	EtudepayeColCode          string
	EtudepayeNbpaye           string
	EtudepayeNotifEngagement  string
	EtudepayeLettreEngagement string
	EtudepayeDeliberation     string
	EtudepayeConvention       string
}
